blank_issues_enabled: false
contact_links:
  - name: â“ Question
    url: https://discord.gg/cxSFkPZdsV
    about: Ask a question
  - name: ğŸ“„ Feature request
    url:  https://github.com/retejs/rete/discussions/631
    about: Request a new feature or enhancement
  - name: ğŸ–‡ï¸ Frameworks integration
    url:  https://github.com/retejs/rete/discussions/635
    about: Discuss integration possibilities with various frameworks
  - name: ğŸ’– Support us on Patreon
    url: https://www.patreon.com/bePatron?u=7890937
    about: Support us on Patreon to help the project grow
  - name: ğŸ’° Donate via OpenCollective
    url: https://opencollective.com/rete/donate
    about: Donate to our project via OpenCollective
